### ISSUE TITLE
Crash due to call to undefined method

### ISSUE THREAD

**Issue by DarkDust** [Nevay/spi#3]
Updating Drupal brought this package as a new dependency. But it makes `composer update` crash:

```
Fatal error: Uncaught Error: Call to undefined method Composer\Util\Platform::getCwd() in /path/to/drupal/vendor/tbachert/spi/src/Composer/Plugin.php:192
Stack trace:
#0 /path/to/drupal/vendor/tbachert/spi/src/Composer/Plugin.php(72): Nevay\SPI\Composer\Plugin->serviceProviders()
#1 /path/to/drupal/vendor/tbachert/spi/src/Composer/Plugin.php(64): Nevay\SPI\Composer\Plugin->dumpGeneratedServiceProviderData()
#2 [internal function]: Nevay\SPI\Composer\Plugin->preAutoloadDump()
#3 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(192): call_user_func()
#4 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(119): Composer\EventDispatcher\EventDispatcher->doDispatch()
#5 /usr/share/php/Composer/Autoload/AutoloadGenerator.php(194): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#6 /usr/share/php/Composer/Installer.php(341): Composer\Autoload\AutoloadGenerator->dump()
#7 /usr/share/php/Composer/Command/UpdateCommand.php(248): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\UpdateCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(84): Composer\Console\Application->run()
#15 {main}
  thrown in /path/to/drupal/vendor/tbachert/spi/src/Composer/Plugin.php on line 192
```

System infos:

```
Ubuntu 22.04.5 LTS
 % composer --version
Composer 2.2.6 2022-02-04 17:00:38
 % php --version
PHP 8.1.2-1ubuntu2.18 (cli) (built: Jun 14 2024 15:52:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.18, Copyright (c), by Zend Technologies
```

**Comment by markfullmer** [comment]
Confirming that I can replicate this error inside a Docker container, running `Composer version 2.2.22`, concurrent with the update in `drupal/core-dev` (https://github.com/drupal/core-dev)

This is newly required because
```
open-telemetry/sdk  1.1.0  requires  tbachert/spi (^1.0.1)  
drupal/core-dev 10.3.5  requires   open-telemetry/sdk (^1)       
```

As an immediate workaround, Drupal developers can switch from `drupal/core-dev:^10` to `drupal/core-dev-pinned:^10`. See https://github.com/drupal/core-dev-pinned

**Comment by DarkDust** [comment]
That was fast, kudos!
